<div class="sub-menu">
                  <ul>
                    <li class="meni-item">
                      <h6><a href="#">Shop Catalog</a></h6>
                      <ul class="sub-menu1">
                        <li><a href="#">Shop - Catagory Grid</a></li>
                        <li><a href="#">Shop - Catagory Grid</a></li>
                        <li><a href="#">Shop - Catagory Grid</a></li>
                        <li><a href="#">Shop - Catagory Grid</a></li>
                        <li><a href="#">Shop - Catagory Grid</a></li>
                        <li><a href="#">Shop - Catagory Grid</a></li>
                        <li><a href="#">Shop - Catagory Grid</a></li>
                        <li><a href="#">Shop - Catagory Grid</a></li>
                        <li><a href="#">Shop - Catagory Grid</a></li>
                        <li><a href="#">Shop - Catagory Grid</a></li>
                      </ul>
                    </li>
                    <li class="meni-item">
                      <h6><a href="#">Product Type</a></h6>
                      <ul class="sub-menu1">
                        <li><a href="#">Simple</a></li>
                        <li><a href="#">Variable</a></li>
                        <li><a href="#">Grouped</a></li>
                        <li><a href="#">External / Affiliate</a></li>
                        <li><a href="#">Out of Stock</a></li>                       
                      </ul>
                    </li>
                    <li class="meni-item">
                      <h6><a href="#">Product Layouts</a></h6>
                      <ul class="sub-menu1">
                        <li><a href="#">No Background</a></li>
                        <li><a href="#">Shop - Catagory Grid</a></li>
                        <li><a href="#">Shop - Catagory Grid</a></li>
                        <li><a href="#">Shop - Catagory Grid</a></li>
                        <li><a href="#">Shop - Catagory Grid</a></li>
                        <li><a href="#">Shop - Catagory Grid</a></li>
                        <li><a href="#">Shop - Catagory Grid</a></li>
                        <li><a href="#">Shop - Catagory Grid</a></li>
                        <li><a href="#">Shop - Catagory Grid</a></li>
                        <li><a href="#">Image Zoom</a></li>
                      </ul>
                    </li>
                    <li class="meni-item">
                      <h6><a href="#">Shop Pages</a></h6>
                      <ul class="sub-menu1">
                        <li><a href="#">Cart</a></li>
                        <li><a href="#">Order Tracking</a></li>
                        <li><a href="#">My Account </a></li>
                        <li><a href="#"> wishlist </a></li> 
                      </ul>
                    </li>
                  </ul>
                </div>